package raf.dsw.classycraft.app.observer;

public enum NotificationType {
    MESSAGE,DIAGRAM_REMOVED,DIAGRAM_ADDED,PACKAGE_REMOVED,PROJECT_REMOVED,PROJECT_NAME_CHANGED,DIAGRAM_NAME_CHANGED, ADD, REMOVE
}
